services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    env_file:
      - .env
    command: >
      bash -c "composer install && php artisan key:generate && php artisan migrate && chmod +x ./seeder.sh && ./seeder.sh && php-fpm"

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
